model_input:
  categorical_features:
    - bairro
  numerical_features:
    - area
    - rooms
    - bathrooms
    - garages
  target: price

model_training:
  use_grid_search: False
  grid_search:
    param_grid:
      max_depth: [3, 5, 7]
      n_estimators: [50, 75, 100]
      subsample: [.8, .9, 1]
      colsample_bylevel: [.8, .9, 1]
  without_grid_search:
    best_params:
      max_depth: 7
      n_estimators: 100
      subsample: .9
      colsample_bylevel: .8
